### ISSUE TITLE
github: is a valid dependency format for npm

### ISSUE THREAD

**Issue by kdex** [jspm/npm#101]
In [`npm.js`, line 257](https://github.com/jspm/npm/blob/dd487aa505aafc1ea04ce725826b1c906877422b/lib/npm.js#L257), you're making wrong assumptions about `npm`'s dependency format. 

Note that some valid dependency formats include:

- `github:owner/repository` 
- `https://github.com/owner/repository.git`

You can find a more thorough list [here](https://docs.npmjs.com/files/package.json).

Could you add support for more formats, please?

**Comment by guybedford** [comment]
Thanks for posting. The `https://github.com` case is filtered out in the first part of the conditional.

I did not know `github:owner/repo` was a valid dependency format on npm? It is not listed in https://docs.npmjs.com/files/package.json#dependencies.

**Comment by kdex** [comment]
By now, I'd have to guess, but it might have been me trying to specify this URL in `package.json` directly, without prepending a specific registry (which would then of course lead to an awkward case where `https` is assumed to be a registry).

Syntactically, does the format:

```js
npm:${string}
```

assume that `string` is anything that would work in npm commands like the following?

```js
npm install -D ${string}
```

Or will it instead check **only** against the npm registry (without resolving special formats like `owner/repository` and the like)?

About the `package.json` documentation: Oh, it might be slightly out of date, then. Anyway, you might be able to reproduce this using the following syntax:

```bash
$ npm --version
3.3.6
$ npm install -D kdex/event-emitter
```
will lead to the following line in `devDependencies`:
```json
    …
    "cross-json": "github:kdex/cross-json",
    …
```

Can you reproduce this?

**Comment by guybedford** [comment]
Thanks, you're completely right, we should support this.

**Comment by neothemachine** [comment]
The issue with this is that it requires to actually build the package first, otherwise some packages may just end up broken. Packages published on npm are already built (ignoring postinstall for now) but using a direct git dependency means it potentially needs the build step (or install or prepublish or whatever npm phase that corresponds to). I wouldn't worry too much about security when running scripts since the user opts-in to that by using a "source" dependency.

In my case, the build step is just transpilation (which however is the difference between src/ vs transpiled/ folders and having the correct path in "main").

**Comment by guybedford** [comment]
@neothemachine the build operations are a separate issue to this one I believe, which has actually been fixed. Happy to continue that discussion though.
