### ISSUE TITLE
browser main not being properly resolved

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#144]
eg `jspm install npm:snabbdom-to-html` has in the derived package config for the main (src/index.js):

```javascript
    "./src/index.js": {
      "browser": "./lib/"
    },
```

which is then not fully resolved. We should ensure that the conditional maps go through the full resolution process including index.js addition.

**Comment by perrin4869** [comment]
@guybedford any update on this issue? Any chance of this landing in the near future? Thanks!

**Comment by perrin4869** [comment]
hm... just tried jspm@0.17-beta.26, but the resolution for `browser` is still the same...

**Comment by perrin4869** [comment]
hm... looking at `jspm_packages/npm/snabbdom-to-html@2.1.3.json`:

```
{
  "main": "src/index.js",
  "format": "cjs",
  "meta": {
    "*.json": {
      "format": "json"
    }
  },
  "map": {
    "./lib": "./lib/index.js",
    "./src": "./src/index.js",
    "./src/index.js": {
      "browser": "./lib/"
    },
    "./test": "./test/index.js"
  }
}
```

Since `main` points to `./src/index.js`, which on the `browser` points to `./lib/` and `./lib` points to `./lib/index.js`, shouldn't the main in the browser resolve to `./lib/index.js`, even without fully resolving `browser` to `./lib/index.js`?

`main -> ./src/index.js -(browser)> ./lib/ -> ./lib/index.js`

**Comment by perrin4869** [comment]
ok clearing the jspm cache at `~/.jspm` fixed the problem ><;;

**Comment by guybedford** [comment]
👍
