### ISSUE TITLE
Support prerelease wildcards

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#49]
Apparently this is supported in npm:

```
<=0.13.0-rcx
```

We should add this to the conversion.

**Comment by crisptrutski** [comment]
@guybedford

Took a look at npm's handling of this, looks like `x` is not actually being treated as a wildcard here. It just relies on `x >= [0-9a-x]`, ie. don't hope for `0.13.0-rcy` to resolve.

Also, do you mean `>=` instead of `<=`? Not sure why you'd want a range that includes `0.13.0-rc1` but excludes `0.13.0`.

Perhaps provide a link to the bug reports that lead to this issue?

**Comment by guybedford** [comment]
@crisptrutski thanks the issue was https://github.com/jspm/jspm-cli/issues/383#issuecomment-77728147, which means this is actually an issue with our parsing of ranges.

It is common for peerDependencies to use strange ranges, which I think we can solve by just allowing peer dependencies to have warnings when out-of-range that don't throw. This is being tracked in the jspm peerDependencies support issue.

Closing this for now as a non issue.
