### ISSUE TITLE
Support clearing config

### ISSUE THREAD

**Issue by crisptrutski** [jspm/npm#68]
Overheard from @guybedford:

If explicit [auth / registry] configuration is present, configure wizard should have a prompt which allows the user to clear this option.

**Comment by crisptrutski** [comment]
Guessing the rationale here is making it simple to just track an `.npmrc` file instead

**Comment by crisptrutski** [comment]
@guybedford is this how you imagine it:

#### No configuration:

`set value for this thing [inferred default]`

#### Has configuration

`would you like to clear configuration for this thing? [no]` *if [yes], wipe and move to next 'thing'*
`set value for this thing [current config]` *only asked if [no]*

**Comment by guybedford** [comment]
Maybe on the first step of `npmrc found, would you like to use these settings` we let that stop all successive prompts entirely?

Then if the user has a value set, it reads: `custom settings being used currently, would you like to revert to the npmrc defaults?` which does the same thing.

Only when the user selects no, do we then allow custom auth and custom registry settings.

We then don't let the user enter custom auth but not custom registry settings or vice versa, via these prompts. If they did do it manually directly in the config file, things do work out as expected though.

Thoughts?

**Comment by crisptrutski** [comment]
Find the idea of "would you like to use these settings" clearing a bunch of config a bit heavy handed - user may have forgotten what is currently configured. The objective to not "freeze" defaults by letting them be saved, ever, has been a prevalent approach, and that feels simpler here.

1. If an option is configured, a yes/no step whether it should be changed

2. Setting the value, with the implication that accepting a default means that no value would be saved.

This results in a trim and unambiguous flow in each case (opting in and out of defaults, changing in place, or accepting defaults).

Additionally the fact that it's flat means that it'll always be familiar, and does not require maintenance around "which values should be cleared".

**Comment by guybedford** [comment]
Yes, I understand, this was the initial proposal more or less. Here are some use cases to consider:

1. User has npmrc configured correctly, their npm registry in jspm just works and they never have to think about it.
2. User has no npmrc, but does have a company-level npm setup or scoped npm setup. They run `jspm registry config npm`, get no npmrc prompt, use the default registry option, and enter their authentication credentials.
3. User has existing npmrc options saved into jspm config. The registry value is the default npm registry. They run `jspm registry config npm` because they want to switch over to using their private npm registry. They have these options in their npmrc file already, so are able to switch into this by selecting yes on the first prompt.
4. New jspm user wants to set jspm to load directly from the public npm registry with their public user name instead of the private npm setup they have in their company and in the npmrc. By selecting no on the first prompt, they are able to enter their own custom details.

In all the above cases, npmrc credentials consist of the registry plus the auth. They get either both configured, or both reverted to npmrc. If you have a use case where one would want to separate these, I'm more than happy to consider it - was just trying optimizing for the above use cases.
