### ISSUE TITLE
Private npm setup registry option

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#80]
When setting up a private npm registry, the default base-level registry should remain as npm.

The private registry itself should be linked to either all scopes or some scopes. And then the global npm registry should defer to the private registry for those scopes.

The configuration to do the above should be done by the private npm registry configuration. Note this does involve the private npm registry configuring the main npm registry as well, so we need to work that out.

**Comment by guybedford** [comment]
Perhaps the scope mapping is a global config not tied to the registries? And we allow registries to have this global shared configuration space.

**Comment by adamdicarlo** [comment]
Modeling after the way `npm` handles it would definitely be a great starting point - .npmrc stores

```ini
@company:registry=http://private-npm.example.com/artifactory/api/npm/company-js-local/
@extrascope:registry=http://private-npm.example.com/artifactory/api/npm/company-js-local/
//private-npm.example.com/artifactory/api/npm/company-js-local/:_password=....==
//private-npm.example.com/artifactory/api/npm/company-js-local/:username=person
//private-npm.example.com/artifactory/api/npm/company-js-local/:email=person@company.com
//private-npm.example.com/artifactory/api/npm/company-js-local/:always-auth=true
```
in that case configuring what registry to use for the scopes `@company` and `@extrascope`.

then you have config for non-scoped modules (if you don't want to use the public npm), e.g.

```ini
registry=http://private-npm.example.com/artifactory/api/npm/js-virtual/
```

the main purpose of which would be that your private npm is mirroring the public npm (and maybe you have it set up to allow only certain modules via a whitelist or some such).

However, you might have un-scoped modules set to some other npm instance. the example above is one way you can configure Artifactory's npm, but I might want to use a separate npm registry, for unscoped modules, that just does the public registry mirroring.

To perhaps complicate things further, the public npm registry will / already has scopes, too. But if you're specifying on a scope by scope basis which registry to use that should be fine. (Given the example configs above, if I try to install `@company/foo`, it will use my private npm; if I try to install, e.g., `@newrelic/worlds-best-package` it would use public npm since @newrelic is not configured in the npmrc.)

**Comment by mattfysh** [comment]
Guy,

One of the reasons we use a private internal registry (Sinopia) is to protect ourselves from public registry downtime, as Sinopia will almost always have a cached copy of the required library. When you say 'all scopes' do you also mean the set of packages with 'no scope' i.e. the public registry packages?

Cheers,

**Comment by guybedford** [comment]
@mattfysh yes I'm tempted to no longer encourage creating custom npm registries in jspm as npm scopes seem to capture everything we want here anyway. Just configure the npm registry to use the private registry, and set up the scope configurations the same way. Would something like that work for you here?

**Comment by mattfysh** [comment]
Yes, that's perfect. Thank you!

**Comment by guybedford** [comment]
Tracking in https://github.com/jspm/npm/issues/94.
