### ISSUE TITLE
Support array main

### ISSUE THREAD

**Issue by guybedford** [jspm/npm#85]
For some mysterious reason Node seems to support array mains, where each main is attempted in sequence until one works. We should therefore support this process.

**Comment by kubawalinski** [comment]
@guybedford Thanks for filing this issue after seeing my gitter question. For the record the original repo for which I noticed this problem was https://github.com/angular-ui/bower-ui-grid. On npm this package is available as "angular-ui-grid".

Will fixing this in the npm module also take care of the fact that installation from github is not successful because no main entry point was found? Or should I file an issue on a different repo for this one?

**Comment by guybedford** [comment]
After testing this in Node it is certainly not supported by Node. I don't believe npm would directly support it either.
